/*
 * Copyright (c) Contributors http://github.com/aduffy70/Chat-Logger
 * See CONTRIBUTORS.TXT for a full list of copyright holders.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Chat-Logger Module nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


using System;
using System.Collections.Generic;
using System.Reflection;

using log4net;
using Nini.Config;
using OpenMetaverse;

using OpenSim.Framework;
using OpenSim.Region.Framework;
using OpenSim.Region.Framework.Interfaces;
using OpenSim.Region.Framework.Scenes;

using Mono.Addins;

[assembly: Addin("ChatLoggerModule", "0.1")]
[assembly: AddinDependency("OpenSim", "0.5")]
namespace ChatLoggerModule
{
    [Extension(Path="/OpenSim/RegionModules",NodeName="RegionModule")]
	public class ChatLoggerModule : INonSharedRegionModule
	{
	    //Set up console logging and dialog messages
		private static readonly ILog m_log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
		IDialogModule m_dialogMod;

        //Configurable settings read from ChatLogger.ini
		bool m_enabled;
        string m_logPath; //Path to the folder where logs will be stored - defaults to the bin folder
        int m_commandChannel; //module listens for commands on this channel
        string m_instanceTag; //unique string to identify files generated by this instance

        int m_logChannel = 0; //Module logs all chat heard on this channel
        string m_chatLog; //Path and filename of the chat log
		Scene m_scene;
		bool m_logging = false; // Tracks whether chat is being logged

		#region INonSharedRegionModule interface

        public void Initialise(IConfigSource config)
		{
            //Read configuration settings
            IConfig chatLoggerConfig = config.Configs["ChatLogger"];
			if (chatLoggerConfig != null)
			{
				m_enabled = chatLoggerConfig.GetBoolean("enabled", false);
                m_logPath = chatLoggerConfig.GetString("log_path", "./");
                m_instanceTag = chatLoggerConfig.GetString("instance_tag", "myregion");
                m_commandChannel = chatLoggerConfig.GetInt("command_channel", 18);
                if (m_commandChannel == 0)
                {
                    m_enabled = false;
                    m_log.WarnFormat("[ChatLogger]: Command channel cannot be 0.  Disabling module...");
                }
			}
			if (m_enabled)
			{
				m_log.Info("[ChatLogger]: Initializing...");
				m_log.Info(String.Format("[ChatLogger] Log Path: {0}, Command Channel: {1}, Instance Tag: {2}", m_logPath, m_commandChannel, m_instanceTag));
            }
        }

        public void AddRegion(Scene scene)
        {
            if (m_enabled)
            {
                m_scene = scene;
                m_chatLog = System.IO.Path.Combine(m_logPath, m_instanceTag + "-chat.log");
                m_scene.EventManager.OnChatFromClient += OnClientChat; //Avatar chat
                m_scene.EventManager.OnChatFromWorld += OnWorldChat; //Object chat
                m_scene.EventManager.OnChatBroadcast += OnBroadcast; //Module chat (e.g., the IRCBridge Module)
                m_scene.EventManager.OnMakeRootAgent += OnVisit; //Avatars entering region
                m_dialogMod = m_scene.RequestModuleInterface<IDialogModule>();
            }
        }

        public void RemoveRegion(Scene scene)
        {
        }

        public void RegionLoaded(Scene scene)
        {
        }

        public void Close()
		{
        }

        public string Name
		{
            get
            {
                return "ChatLoggerModule";
            }
        }

        public Type ReplaceableInterface
        {
            get
            {
                return null;
            }
        }

        #endregion

        void OnVisit(ScenePresence presence) //Each avatar entering the region is notified if chat is being logged.
        {
            if (m_logging == true)
            {
                if (m_dialogMod != null)
                {
                    m_dialogMod.SendAlertToUser(presence.ControllingClient, "Chat Logger is active - All chat will be logged...", true);
                }
            }
        }

		void OnClientChat(Object sender, OSChatMessage chat)
		{
            if ((chat.Message == "") || ((chat.Channel != m_logChannel) && (chat.Channel != m_commandChannel))) //Ignore empty messages or messages not on the log channel or command channel
            {
				return;
            }
			else if ((chat.Channel == m_logChannel) && (m_logging == true)) //Chat to be logged
            {
                //string senderName = m_scene.GetUserName(chat.SenderUUID);
                ScenePresence sp = m_scene.GetScenePresence(chat.SenderUUID);
                string senderName = sp.Firstname + " " + sp.Lastname;
                LogChat(senderName, chat.Message);
            }
            else if (chat.Channel == m_commandChannel) //Commands for the module
            {
                ProcessCommand(chat.Message.ToLower());
			}
		}

		void OnWorldChat(Object sender, OSChatMessage chat)
		{
            if ((chat.Channel != m_logChannel) && (chat.Channel != m_commandChannel)) //Ignore messages not on the log channel or command channel
            {
				return;
            }
			else if ((chat.Channel == m_logChannel) && (m_logging == true)) //Chat to be logged
            {
                LogChat(chat.From, chat.Message);
            }
            else if (chat.Channel == m_commandChannel) //Commands for the module
            {
                ProcessCommand(chat.Message.ToLower());
			}
		}

		void OnBroadcast(Object sender, OSChatMessage chat)
		{
            if ((chat.Channel != m_logChannel) && (chat.Channel != m_commandChannel)) //Ignore empty messages or messages not on the log channel or command channel
            {
				return;
            }
			else if ((chat.Channel == m_logChannel) && (m_logging == true)) //Chat to be logged
            {
                LogChat("**Broadcast**", chat.Message); //If I knew all the possible sources of Broadcasts I could have the actual source displayed instead of **Broadcast**
            }
            else if (chat.Channel == m_commandChannel) //Commands for the module
            {
                ProcessCommand(chat.Message.ToLower());
			}
		}

        void LogChat(string sender, string message)
        {
            System.IO.StreamWriter logFile = System.IO.File.AppendText(m_chatLog);
            logFile.WriteLine("[" + DateTime.Now + "] " + sender + ": " + message);
            logFile.Close();
        }

        void ProcessCommand(string message)
        {
            if (message == "off")
            {
                if (m_logging == true)
                {
                    m_logging = false;
                    DialogToAll("Chat Logger: Off - Chat will NOT be recorded...");
                }
                else
                {
                    DialogToAll("Chat Logger: Cannot stop logging because logging is already off...");
                }
            }
            else if (message == "on")
            {
                if (m_logging == false)
                {
                    m_logging = true;
                    DialogToAll("Chat Logger: On - All chat will be recorded...");
                }
                else
                {
                    DialogToAll("Chat Logger: Cannot start logging because chat is already being logged");
                }
            }
            else if (message == "reset")
            {
                if (m_logging == true)
                {
                    DialogToAll("Chat Logger: Cannot reset while chat is being logged...");
                }
                else
                {
                    DialogToAll("Chat Logger: Reset - Clearing the chat log. Chat will NOT be recorded...");
                    System.IO.File.Delete(m_chatLog);
                }
            }
            else
            {
                DialogToAll("ChatLogger: Invalid command...");
            }
        }

        void DialogToAll(string dialogMessage) //All avatars in the region are notified when logging is turned on, off, or the log is cleared
        {
            if (m_dialogMod != null)
            {
                m_dialogMod.SendGeneralAlert(dialogMessage);
            }
        }
    }
}
